### ISSUE TITLE
[번역]enterprise scale에서 ArgoCD를 통한 CD의 비밀 재료

### ISSUE THREAD

**Issue by sangheee** [sangheee/algorithm#11]
https://akuity.io/blog/unveil-the-secret-ingredients-of-continuous-delivery-at-enterprise-scale-with-argocd-kubecon-china-2021/

scale이 커지다보면 어느순간 튜닝이 필요해지는 시점이 온다
Argo CD component인 **application controller, repo server, API server** 각각의 관점에서 튜닝 가능한 포인트를 짚어본다.

## TL;DR
- **controller-server**
  - application 많아지면 cm의 `controller.status.processors`로 worker 수 늘리자, 
  resource 더 쓰니까 resource limit도 잊지 말고 늘리자.
  - 한 instance가 resource 넘 많이 쓰면 sts `spec.replicas`, cm의 `ARGOCD_CONTROLLER_REPLICAS`로 multiple instance(sharding) 하자~
- **repo-server**
  - config management tool(Helm, Kustomize, Jsonnet)을 사용한 application을 통해 manifest generation 할 경우 **replica 수 늘려서 빠르게** 할 수 있음
  - cluster의 모든 manifest 때려박는 mono repository는 cache를 invalidate하므로 주의, repository를 적절히 쪼개라~
  - 동시에 많은 manifest generation하다 OOM 날 수 있으니까 `reposerver.parallelism.limit`으로 조절해라~
- **API server**는 deploy memory limit 조정

### Too Many Applications
- Argo CD controller는 multiple worker가 동작하며,
**각 worker는 각각의 application을 reconcile하는 pipeline을 구축한다.**
![image](https://user-images.githubusercontent.com/29528531/168467985-ca9e5ab4-5c1c-4fae-9a1b-058dd619daad.png)

- worker 수 기본 값은 20이다. 일반적으로 수백개의 application을 처리하기에 충분하다.
- application 수가 1000단위 이상이 되면 슬슬 delay 발생하기 시작하는데 application 배포하면 할수록 delay 길어질 것 ㅇㅇ
- delay를 줄이기 위해 controller worker 수를 늘릴 수 있다.
```yaml
# https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  ...
  name: argocd-application-controller
spec:
    spec:
      ...
      containers:
      - command:
        - argocd-application-controller
        env:
        ...
        - name: ARGOCD_APPLICATION_CONTROLLER_STATUS_PROCESSORS
          valueFrom:
            configMapKeyRef:
              key: controller.status.processors
              name: argocd-cmd-params-cm
              optional: true
        ...
---
apiVersion: v1
kind: ConfigMap
metadata:
  ...
  name: argocd-cmd-params-cm
data:
  # Number of application status processors (default 20)
  controller.status.processors: "100"
```
- **worker는 CPU와 memory를 소비한다, controller sts의 resources requests, limit도 함께 조정해주어야 한다!!**

### Too Many Clusters
- application이 증가함에 따라 controller는 한 instance로는 벅찬 CPU와 memory가 필요해질 것이다.
- 이 때, **controller sharding feature**를 이용해 controller를 multiple instance로 동작시켜 개별 instacne의 computational resource의 사용을 줄일 수 있다.
- `argocd-application-controller` sts의 `spec.replicas` 변경을 통해 controller를 sharding
- cm 또는 env로 **`ARGOCD_CONTROLLER_REPLICAS`도 sts의 replicas와 같은 수로 변경해야 한다.**<img width="602" alt="스크린샷 2022-05-15 오후 6 45 39" src="https://user-images.githubusercontent.com/29528531/168466735-0a25f2d5-dfd2-40d1-a791-b7505e45a2d0.png">

### Manifest Generation 
- 일반적으로 plain yaml repo server는 문제가 안된다.
- 문제는 Helm, kusomize, jsonnet 같은 config management tools를 쓸 때이다.
  - 이 tool들을 (as you know~) 개발자들이 manifests의 중복을 피하고 쉽게 다양하게 변경할 수 있게 돕는다, 아 왜쓰는지 RGRG. 근데...
- 이러한 config management tool로 된 manifest를 통해 정의된 application은 runtime에 manifest generation을 수행해야하는 overhead가 있다는 거지
  - manifest generation 을 위해 추가적인 config management tool exec/folk 필요하고 이것들은 memory, CPU가 필요
- **manifest generation 빨리 하고 싶으면 repo-server replicas 늘려달라~**

### Mono Repositories
- 수백, 수천개의 git repositories 처리에 3-4개의 repo-server면 충분하다.
- ArgoCD는 생성된 manifests를 aggressively cache 하기 때문에 자주 manifests를 재생성할 필요가 없다.
- 그러나!! **if you store deployment manifests in so-called mono repositories, some performance issues occur!!!**
 
![image](https://user-images.githubusercontent.com/29528531/168468810-1cf02b42-6fce-4f52-81d7-f35ce1b86860.png)

- 필요한 cluster의 전체 상태를 표현하기 위해 이러한 (infrastructure부터 multiple microservices를 포함하는) mono repositories를 사용하곤 한다.
- **그러나 이러한 mono repo로의 각각의 commit은 cache를 invalidate하게 한다.**
  - **ArgoCD가 갑자기 수백개 application의 manifest를 재생성하면서 CPU/Memory spike가 발생할 수도 있다..!**
  - config management tools은 동시 manifest 생성을 지원하지 않으며 의존성이 있는 application은 순차로 처리되어야 하는데도...!

### Limit Parallelism
- 한 번에 너무 많은 manifest 생성은 CPU와 memory spike를 발생시킬 수 있다. OOM kill 위험 있으니 주의 필요!
- cm 또는 env의 `reposerver.parallelism.limit`를 통해 동시에 생성 가능한 manifest 수를 제한할 수 있다.
- repo-server deploy의 resource memory limit에 따라 수를 조정 ㅇㅇ

## 3. API Server
API server는 resource가 많이 필요 없고, 수평적으로 확장 가능한 stateless server다. 
뭐..그래서 ... API server는 모든 ArgoCD applications를 위한 in-memory cache가 있는데 필요하면 memory limit이나 늘리든가..
