### ISSUE TITLE
kro: Kube Resource Orchestrator

### ISSUE THREAD

**Issue by sangheee** [sangheee/algorithm#25]
https://github.com/kro-run/kro
https://kro.run/

tl;dr: 범용적 operator 느낌? customAPI가 정의된 RG(ResourceGroup)이 배포해야할 리소스를 맥락에 맞게 처리하는 듯 하다.

> Helm, Kustomize 같은 클라이언트 측 템플릿 도구나 user-defined controller 등을 개발해야 했으나, 이는 유지보수 비용이 높고 비전문가에게는 복잡한 솔루션이었습니다. 이러한 문제를 해결하기 위해 Google, AWS, Microsoft가 협력하여 Kubernetes API를 단순화한 kro를 개발하였습니다.

## What is kro
>  With kro, you can easily configure new custom APIs that create a group of Kubernetes objects and the logical operations between them.

- kro leverages [CEL (Common Expression Language)](https://github.com/google/cel-spec)

- The Developers call the **Custom API**, which creates resources such as the **Deployment, Ingress, ServiceAccount, Prometheus Monitor, IAM Role, IAM Policy**, and **Amazon S3 Bucket**. This allows the Developers to easily manage and deploy their applications in a standardized and streamlined manner.
  (Fugure 1: End user interface - Custom API)
  ![Image](https://github.com/user-attachments/assets/7c9568df-3805-4cb7-99a5-67959b44dec9)

- When you install Kro in your cluster, it installs a Custom Resource Definition (CRD) called **ResourceGraphDefinition (RG)**.
-  The Developers no longer need to directly manage the underlying infrastructure complexities, as the custom API handles the deployment and configuration of the required resources.

**Comment by sangheee** [comment]
## [ResourceGraphDefinitions](https://kro.run/docs/concepts/resource-group-definitions)
> **ResourceGraphDefinitions provide a way to define, organize, and manage sets of related Kubernetes resources as a single, reusable unit.**

- A ResourceGraphDefinition is a custom resource that lets you create new Kubernetes APIs for deploying multiple resources together. 
  - How resources reference each other (dependencies) 
  - When resources should be included (conditions)
등도 명세 가능

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-resourcegraphdefinition # Metadata section
spec:
  schema: # Define your API
    apiVersion: v1alpha1 # API version
    kind: MyAPI # API kind
    spec: {} # fields users can configure
    status: {} # fields kro will populate

  # Define the resources kro will manage
  resources:
    - id: resource1
      # declare your resources along with default values and variables
      template: {}
```
- Example Schema
```yaml
schema:
  apiVersion: v1alpha1
  kind: WebApplication # This becomes your new API type
  spec:
    # Fields users can configure using a simple, straightforward syntax
    name: string
    image: string | default="nginx"
    replicas: integer | default=3
    ingress:
      enabled: boolean | default=false

  status:
    # Fields kro will populate automatically from your resources
    # Types are inferred from these CEL expressions
    availableReplicas: ${deployment.status.availableReplicas}
    conditions: ${deployment.status.conditions}
```
  - The schema section defines your new API's structure. 


```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: web-application
spec:
  schema:
    apiVersion: v1alpha1
    kind: WebApplication
    spec:
      # Basic types
      name: string | required=true description="My Name"
      replicas: integer | default=1 minimum=1 maximum=100
      image: string | required=true

      # Structured type
      ingress:
        enabled: boolean | default=false
        host: string | default="example.com"
        path: string | default="/"

      # Array type
      ports: "[]integer"

      # Map type
      env: "map[string]string"

    status:
      # Status fields with auto-inferred types
      availableReplicas: ${deployment.status.availableReplicas}
      serviceEndpoint: ${service.status.loadBalancer.ingress[0].hostname}

  # Define the resources this API will manage.
  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name} # Use the name provided by user
        spec:
          replicas: ${schema.spec.replicas}
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.image} # Use the image provided by user
                  ports:
                    - containerPort: 80
    - id: ingress
      includeWhen:
        - ${schema.spec.ingress.enabled} # Only include if the user wants to create an Ingress
      template:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: ${schema.spec.name}-ingress
        spec:
          rules:
            - http:
                paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                      service:
                        name: ${service.metadata.name} # Use the service name
                        port:
                          number: 80                
```
